name: event-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas>=2.1.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pydantic==2.4.2
    - python-dotenv==1.0.0
    - httpx==0.25.1
    - sqlalchemy==2.0.23
    - aiosqlite==0.19.0
    - openai==1.3.0 